# -*- coding: utf-8 -*-
"""Stop_Building_Chatbots_Start_Building_AI_Agents_That_Act_LangChain_for_Beginners_Part_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B8lotdRLaqJpCOIGRcEN9dxIz2a4X-Tr

### 📘 Video 5: Make AI Use Tools (Agents 101)

**Goal**: Teach your AI to decide when to use tools — no API keys, no parsing errors.

✅ Uses Hugging Face + LangChain

✅ Runs on free Colab GPU

🛠️ Let's build a *true* agent — the right way.

📌 All code available on GitHub:
[github.com/illustris-admin/ai/tree/main/langchain-for-beginners](https://github.com/illustris-admin/ai/tree/main/langchain-for-beginners)
"""

# Install required libraries
!pip install -q langchain-huggingface duckduckgo-search transformers torch accelerate bitsandbytes langchain-community ddgs

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from langchain_huggingface import HuggingFacePipeline

# Load TinyLlama
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype="auto",
    trust_remote_code=True
)

# Create pipeline
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=100,
    temperature=0.3,
    do_sample=True,
    pad_token_id=tokenizer.eos_token_id
)

# Wrap with LangChain
llm = HuggingFacePipeline(pipeline=pipe)

print("✅ Model loaded!")

"""### 🛠️ Define Tools"""

from langchain_community.utilities import DuckDuckGoSearchAPIWrapper

# Web search tool
search = DuckDuckGoSearchAPIWrapper()
def search_tool(query: str) -> str:
    return search.run(query)

# Calculator tool
def calculator_tool(expr: str) -> str:
    try:
        return str(eval(expr.strip()))
    except:
        return "Error: Invalid math expression"

"""### 🧠 Build a Reliable Agent Loop"""

def ask_agent(question: str) -> str:
    # Step 1: Ask LLM if it needs a tool
    prompt = f"<|im_start|>system\nYou are a helpful assistant.\nIf the question needs current data, reply 'USE_SEARCH'.\nIf it needs math, reply 'USE_CALC'.\nOtherwise, answer directly.\nOnly say one of: USE_SEARCH, USE_CALC, or your answer.<|im_end|>\n<|im_start|>user\n{question}<|im_end|>\n<|im_start|>assistant\n"

    response = llm.invoke(prompt).strip().lower()

    # Step 2: Act based on decision
    if "use_search" in response:
        print("🔍 Searching the web...")
        context = search_tool(question)[:1000]
        final_prompt = f"<|im_start|>system\nAnswer using only this info:\n{context}<|im_end|>\n<|im_start|>user\n{question}<|im_end|>\n<|im_start|>assistant\n"
        return llm.invoke(final_prompt).strip()

    elif "use_calc" in response:
        print("🧮 Calculating...")
        expr = question.replace('what is', '').replace('?', '').strip()
        return calculator_tool(expr)

    else:
        return response.replace('use_search', '').replace('use_calc', '').strip()

"""### 🧪 Test the Agent"""

print("🤖 Simple Agent Demo\n")

# Math question
q1 = "What is 123 * 456?"
print(f"Q: {q1}")
print(f"A: {ask_agent(q1)}\n")

# Current events
q2 = "Who won the 2024 Eurovision Song Contest?"
print(f"Q: {q2}")
print(f"A: {ask_agent(q2)}")

# Current events
q3 = "Who won the 2025 FIFA soccer cup?"
print(f"Q: {q3}")
print(f"A: {ask_agent(q3)}")

"""### 🎉 Summary

In this notebook, you:

✅ Built a **working AI agent**

✅ Used **search and calculator tools**

✅ Avoided parsing errors completely

💡 You now understand how agents decide when to act

➡️ **Next: Combine memory, tools, and documents into one smart assistant!**

### 🔗 Resources

- [LangChain Docs](https://python.langchain.com)
- [Illustris.org](https://www.illustris.org)

📚 Enroll in Doug’s course: [Leveraging RAG with PostgreSQL](https://www.illustris.org/courses)

🎥 Subscribe: [YouTube @techbits-do](https://www.youtube.com/@techbits-do)

🔗 Connect: [LinkedIn /doug-ortiz-illustris](https://www.linkedin.com/in/doug-ortiz-illustris/)

💾 Code: [github.com/illustris-admin/ai/tree/main/langchain-for-beginners](https://github.com/illustris-admin/ai/tree/main/langchain-for-beginners)
"""